### ISSUE TITLE
discord.abc.GuildChannel Converter not working

### ISSUE THREAD

**Issue by Polsulpicien** [iDevision/enhanced-discord.py#133]
### Summary

discord.abc.GuildChannel Converter isn't working in slash commands

### Reproduction Steps

Create a slash command using discord.abc.GuildChannel as an argument 

### Minimal Reproducible Code

```python
command(self, ctx, channel:discord.abc.GuildChannel=commands.Option...
```

### Expected Results

Get a list of all channel (text, voice, stage,..) in the guild, since it's listed in [docs](https://enhanced-dpy.readthedocs.io/en/latest/ext/commands/commands.html?highlight=textchannel#discord-converters)

### Actual Results

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 291, in create_slash_commands
    payload = command.to_application_command()
  File "/home/pi/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1731, in to_application_command
    "options": [
  File "/home/pi/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1732, in <listcomp>
    cmd.to_application_command(nested=nested + 1) for cmd in sorted(self.commands, key=lambda x: x.name)
  File "/home/pi/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1334, in to_application_command
    options = self._param_to_options(
  File "/home/pi/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1293, in _param_to_options
    option["channel_types"] = application_option_channel_types[annotation]
KeyError: <class 'discord.abc.GuildChannel'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/discord/client.py", line 705, in run
    return future.result()
  File "/home/pi/.local/lib/python3.9/site-packages/discord/client.py", line 684, in runner
    await self.start(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/discord/client.py", line 635, in start
    await self.setup()
  File "/home/pi/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 282, in setup
    await self.create_slash_commands()
  File "/home/pi/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 293, in create_slash_commands
    raise errors.ApplicationCommandRegistrationError(command)
discord.ext.commands.errors.ApplicationCommandRegistrationError: channel failed to converted to an application command.

### Intents

all

### System Information

- Python v3.9.1-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3676+gfcb2d707
- aiohttp v3.7.4.post0
- system info: Linux 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Requested by Gnome!
![image](https://user-images.githubusercontent.com/70817001/147150484-7be855b2-09fa-4c30-9e28-095c419ab1bb.png)

**Comment by Gnome-py** [comment]
The root cause is that [the channel type check](https://github.com/iDevision/enhanced-discord.py/blob/fcb2d707a1445fefb22311dc5ffe1b47d0b9bf55/discord/ext/commands/core.py#L1293) does not expect discord.abc.GuildChannel however it is allowed because the `issubclass` beforehand is being passed GuildChannel.

This could be solved with a specific guard against (`if discord_type == 7 and annotation != discord.abc.GuildChannel`) or changing `application_option_channel_types[annotation]` for `.get(annotation)` and ignoring the failure case.
